### ISSUE TITLE
Issues with multiple series

### ISSUE THREAD

**Issue by TomW1605** [djdembeck/Audnexus.bundle#25] opened 2021-11-01 13:56 UTC
it looks like there are some issues when a book is in more than one series. for example Men at Arms is the 15th book in the Discworld series but the 2nd book in the City Watch sub series and the scraper has put it as discworld book 3 in the sort title.
![image](https://user-images.githubusercontent.com/17092573/139681575-a88df6e6-8197-4097-840e-7b4f277d2c56.png)
i assume this is because of how Audible has it on their page.
![image](https://user-images.githubusercontent.com/17092573/139681909-25ea6ca8-ebc2-463e-9e31-4f44a7e84cf1.png)
is there a way to say have a setting to always use the larger number (most likely to be the main series and not a sub series)?

**Comment by djdembeck** [comment] 2021-11-02 14:45
Interesting. That would be caused by the `subtitle` containing `book 15`. A solution to this might be to not use `subtitle` in the sort field.

**Comment by djdembeck** [comment] 2021-11-02 15:52
This should be resolved by https://github.com/djdembeck/Audnexus.bundle/commit/2022dbd6ef7d3556c83644956023b9baf37ba7e9, you can test it by pulling the `develop` branch.

**Comment by TomW1605** [comment] 2021-11-03 01:31
> Interesting. That would be caused by the `subtitle` containing `book 15`. A solution to this might be to not use `subtitle` in the sort field.

no 15 is the correct number. 2 is the incorrect one. this book is book 15 if the overall series but book 2 of the sub series.

**Comment by djdembeck** [comment] 2021-11-03 01:43
What Asin are you looking at? For me, it shows book 2 position in the first series https://www.audible.com/pd/Men-at-Arms-Audiobook/B0032N8VPS

**Comment by TomW1605** [comment] 2021-11-03 02:02
that is audible being very inconsistent i think. the first book in the subseries is listed the other way round
https://www.audible.com/pd/Guards-Guards-Audiobook/B0032NANJA
my guess is that when the data was entered it was deemed that the order was not important. not sure how best to handle this.

**Comment by djdembeck** [comment] 2021-12-02 21:46
@TomW1605 the API has been updated to use series' as they are from Audible's API, not web (since web can be inconsistent). Let me know if this fixes the behaviour you expected to see. Previously added books are being retroactively updated on the API side so it may take a few days.

**Closed** 2021-12-02 21:50 UTC
Labels: bug

**Comment by TomW1605** [comment] 2021-12-03 06:24
thanks i will give it a few days and then recreate the library and see how it goes
